"""initial schema

Revision ID: 2e60b0d8ca2d
Revises: 
Create Date: 2026-10-09 11:29:48.620904
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2e60b0d8ca2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('hosted_zones',
    sa.Column('id', sa.String(length=21), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hosted_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hosted_zones_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_hosted_zones_user_name', ['user_id', 'name'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('change_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.String(length=21), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('record_name', sa.String(length=255), nullable=True),
    sa.Column('record_type', sa.String(length=10), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['hosted_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_log_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_log_zone_id'), ['zone_id'], unique=False)

    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.String(length=21), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('routing_policy', sa.String(length=20), server_default='SIMPLE', nullable=False),
    sa.Column('set_identifier', sa.String(length=128), server_default='', nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('failover', sa.String(length=10), nullable=True),
    sa.Column('geo_location', sa.JSON(), nullable=True),
    sa.Column('alias_target', sa.JSON(), nullable=True),
    sa.Column('health_check_id', sa.String(length=64), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['hosted_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'name', 'type', 'set_identifier', name='uq_records_zone_name_type_setid')
    )
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_records_zone_id'), ['zone_id'], unique=False)
        batch_op.create_index('ix_records_zone_name', ['zone_id', 'name'], unique=False)

    op.create_table('zone_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.String(length=21), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['hosted_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'key', name='uq_zone_tags_zone_key')
    )
    with op.batch_alter_table('zone_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zone_tags_zone_id'), ['zone_id'], unique=False)

    op.create_table('zone_vpcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.String(length=21), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('vpc_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['hosted_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'region', 'vpc_id', name='uq_zone_vpcs_zone_region_vpc')
    )
    with op.batch_alter_table('zone_vpcs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zone_vpcs_zone_id'), ['zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_vpcs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zone_vpcs_zone_id'))

    op.drop_table('zone_vpcs')
    with op.batch_alter_table('zone_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zone_tags_zone_id'))

    op.drop_table('zone_tags')
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index('ix_records_zone_name')
        batch_op.drop_index(batch_op.f('ix_records_zone_id'))

    op.drop_table('records')
    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_log_zone_id'))
        batch_op.drop_index(batch_op.f('ix_change_log_user_id'))

    op.drop_table('change_log')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('hosted_zones', schema=None) as batch_op:
        batch_op.drop_index('ix_hosted_zones_user_name')
        batch_op.drop_index(batch_op.f('ix_hosted_zones_user_id'))

    op.drop_table('hosted_zones')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
